---
title: "Information Retrieval"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Information Retrieval}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
suppressPackageStartupMessages(library(quanteda))
library(quanteda.proximity)
```

This is an example of using `quanteda.proximity` to solve an information retrieval problem. See [this question](https://stackoverflow.com/questions/44057639/how-to-calculate-proximity-of-words-to-a-specific-term-in-a-document) on Stack Overflow.

```{r data}
song <- "Far over the misty mountains cold To dungeons deep and caverns old We 
must away ere break of day To seek the pale enchanted gold. The dwarves of 
yore made mighty spells, While hammers fell like ringing bells In places deep, 
where dark things sleep, In hollow halls beneath the fells. For ancient king 
and elvish lord There many a gleaming golden hoard They shaped and wrought, 
and light they caught To hide in gems on hilt of sword. On silver necklaces 
they strung The flowering stars, on crowns they hung The dragon-fire, in 
twisted wire They meshed the light of moon and sun. Far over the misty 
mountains cold To dungeons deep and caverns old We must away, ere break of 
day, To claim our long-forgotten gold. Goblets they carved there for 
themselves And harps of gold; where no man delves There lay they long, and 
many a song Was sung unheard by men or elves. The pines were roaring on the 
height, The winds were moaning in the night. The fire was red, it flaming 
spread; The trees like torches blazed with light. The bells were ringing in 
the dale And men they looked up with faces pale; The dragon’s ire more fierce 
than fire Laid low their towers and houses frail. The mountain smoked beneath 
the moon; The dwarves they heard the tramp of doom. They fled their hall to 
dying fall Beneath his feet, beneath the moon. Far over the misty mountains 
grim To dungeons deep and caverns dim We must away, ere break of day,
To win our harps and gold from him!"
```

```{r processing}
toks <- tokens(song,  remove_punct = TRUE, remove_numbers = TRUE, remove_symbols = TRUE, split_hyphens = TRUE) %>% tokens_tolower() %>% tokens_select("fire", window = 15, padding = TRUE)
toks %>% tokens_proximity("fire") %>% docvars("proximity") -> proximity

context_words <- data.frame(token = toks[[1]][proximity[[1]] <= 16], proximity = proximity[[1]][proximity[[1]] <= 16])

aggregate(proximity ~ token, data = context_words, FUN = mean)
```



